package internal

import (
	"database/sql"
	"fmt"
	"log"

	"github.com/absoran/goproject/shared"
	_ "github.com/lib/pq"
)

var db *sql.DB

// init funciton builds first when application builds. Inıtialize db object for use.
func init() {
	var err error
	db, err = sql.Open("postgres", shared.Config.POSTGRESURL)
	if err != nil {
		log.Fatal(err)
	}
	db.Exec("CREATE TABLE IF NOT EXISTS app_user (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,username varchar(45) NOT NULL,email varchar(45) NOT NULL,password varchar(450) NOT NULL)")
}

// TestDb function basically ping db.
func TestDb() {
	err := db.Ping()
	if err != nil {
		log.Fatal(err)
	} else {
		fmt.Println("db connection success")
	}

}
